### PR TITLE
event,event_hash,event_signature,round,swirlds : change hash types

### LINKED ISSUE #40: Change hash types to [u8; 4]
Currently EventHash and EventSignature are ```Vec<u8>```. ```[u8; 4]``` is more performant and has better type safety.

### PR DESCRIPTION
**Pull request by Maxime2**
change hash types to [u8; 32/64]; closes #40

### CODE REVIEW

**Comment by AgustinCB** [comment]
Can you fix the commit message, 0please? Thanks!

**Comment by Maxime2** [comment]
Fixed.

**Comment by AgustinCB** [comment]
It still doesn't appear signed. And I think the first line passes 50 chars.

**Comment by Maxime2** [comment]
Signed and firs line truncated.

**Pull request merged**
